apiVersion: apps/v1
kind: Deployment
metadata:
  name: cscs-example
  namespace: test-cscs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cscs-example
  template:
    metadata:
      labels:
        app: cscs-example
    spec:
      containers:
        - name: cscs-example
          image: ghcr.io/bells17/cscs-example:v0.1.0
